FROM arm64v8/alpine:latest as builder
RUN apk add --no-cache build-base
ADD endlessh.c Makefile /
RUN make

FROM arm64v8/alpine:latest
EXPOSE 2222/tcp
ENTRYPOINT ["/endlessh"]
CMD ["-4vs"]
COPY --from=builder /endlessh /
